# Site settings
title: enogrob Blog
email: enogrob@gmail.com
description: Blogging about Software Development, Data Science, Cloud Computing, Philosophy, Ancient Knowledge among other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://enogrob.github.io" # the base hostname & protocol for your site
twitter_username: enogrob
github_username:  enogrob
# Build settings
markdown: kramdown
destination: /Users/enogrob/TODAY/enogrob.github.io_blog/enogrob.github.io
timezone: America/Sao_Paulo
